name: Build and Release

on:
  push:
    tags:
      - 'v*' # Déclenche uniquement sur des tags qui commencent par 'v'

permissions:
  contents: write
  actions: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # JDK distribution
          java-version: '21'      # Changez selon votre version de Java

      - name: Build with Maven
        run: mvn clean package

      - name: Extract version from pom.xml
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        # `mvn help:evaluate` est utilisé pour extraire la version du POM.

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Utilisez ici le secret PAT
        with:
          tag_name: ${{ github.ref_name }} # Utilise le nom du tag pour la release
          release_name: Release ${{ github.ref_name }} # Utilise le nom du tag pour le nom de la release
          body: |
            Automatic release generated by pushing the tag `${{ github.ref_name }}`
          draft: false
          prerelease: false

      - name: Set Upload URL Environment Variable
        run: |
          UPLOAD_URL="${{ steps.create_release.outputs.upload_url }}"
          # Formater l'URL pour la rendre valide
          UPLOAD_URL="${UPLOAD_URL%\{*}?name=telmi-simple-story-telmiPack-creator-${{ env.VERSION }}.jar"
          echo "UPLOAD_URL=${UPLOAD_URL}" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: target/telmi-simple-story-telmiPack-creator-${{ env.VERSION }}.jar # Remplacez par le chemin du fichier généré
          asset_name: telmi-simple-story-telmiPack-creator-${{ env.VERSION }}.jar       # Nom du fichier dans la release
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Assurez-vous que le PAT est utilisé ici aussi